---
- hosts: concourse-web
  remote_user: vsadmin
  become: yes
  vars:
    consul_use_systemd: true
    vault_iface: ens160
    vault_cluster_disable: true
    concourseci_version: "v3.3.3"
    concourse_web_options:
      CONCOURSE_BASIC_AUTH_USERNAME: myadmin
      CONCOURSE_BASIC_AUTH_PASSWORD: mypasswd
      CONCOURSE_BIND_IP: "0.0.0.0"
      CONCOURSE_TSA_HOST: "{{ groups[concourseci_web_group][0] }}"
      CONCOURSE_TSA_BIND_IP: "0.0.0.0"
      CONCOURSE_TSA_BIND_PORT: "2222"
      CONCOURSE_TSA_AUTHORIZED_KEYS: "{{ concourseci_ssh_dir }}/tsa_authorization"
      CONCOURSE_TSA_HOST_KEY: "{{ concourseci_ssh_dir }}/tsa"
      CONCOURSE_SESSION_SIGNING_KEY: "{{ concourseci_ssh_dir }}/session_signing"
      CONCOURSE_POSTGRES_DATA_SOURCE: "postgres://concourseci:conpass@127.0.0.1/concourse?sslmode=disable"
      CONCOURSE_EXTERNAL_URL: "http://CHANGEME"
  roles:
    - consul
    - vault
    - postgres
    - concourse
  tasks:
  - copy:
      src: "{{ concourseci_bin_dir }}/fly"
      dest: /usr/local/bin/fly
      remote_src: true
      mode: 0755
